FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer /app/consumer
COPY libs /app/libs

CMD ["python", "-m", "consumer.main", "sqs"]
