FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9

COPY requirements.txt ./
RUN pip install -q -r requirements.txt

COPY ./consumer ./consumer
COPY ./libs ./libs

CMD [ "consumer.main.lambda_handler" ]
